@CRM_API_HostAddress = https://localhost:7129
@Token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJDbGllbnQiOiJ0cnVlIiwiSUQiOiJiZjc3YWY0My04MjE1LTQzM2UtOTQ3MS1jOWQwMzZiZTJkNjkiLCJuYmYiOjE3NDI5NTI3OTIsImV4cCI6MTc0Mjk1NDU5Mn0.8ypsda4pCNO7mqi573JEZJr5m3-zzQTE4l-Sg4E1d-o

### Test GET all clients from the stored procedure (Good Case)
GET {{CRM_API_HostAddress}}/Client 
Content-Type: application/json

### Test GET all soft deleted clients from the stored procedure (Good Case)
GET {{CRM_API_HostAddress}}/Backup
Content-Type: application/json
Authorization: {{Token}}

### Test GET client by ID from stored procedure (Good Case)
GET {{CRM_API_HostAddress}}/Client/9e081e68-9437-4f11-97e3-0e7515449806
Content-Type: application/json
Authorization: {{Token}}

### Test GET client by ID from stored procedure (Bad Case - Invalid ID)
GET {{CRM_API_HostAddress}}/Client/3ebdae4f-5aa5-4a80-a63a-be2daa92df81
Content-Type: application/json
Authorization: {{Token}}

### Test POST create new client (Good Case)
POST {{CRM_API_HostAddress}}/Client 
Content-Type: application/json
Authorization: {{Token}}

{
  "TitleId": 1,
  "ClientName": "John",
  "ClientSurname": "Doe",
  "ClientEmail": "john5.doe@example.com",
  "ClientContactNumber": "123-456-7890",
  "ClientAddress": "123 Main St, Anytown, USA",
  "ClientProfilePicture": "iVBORw0KGgoAAAANSUhEUgAA",
  "TypeId": 1,
  "LoginUsername":"john.com",
  "LoginPassword":"password"
}


### Test POST create new client (Bad Case - Missing Client Name)
POST {{CRM_API_HostAddress}}/Client 
Content-Type: application/json

{
  "TitleId": 1,
  "ClientSurname": "Doe",
  "ClientEmail": "john.doe@example.com",
  "ClientContactNumber": "1234567890",
  "ClientAddress": "123 Main St, City, Country",
  "ClientProfilePicture": "iVBORw0KGgoAAAANSUhEUgAA",
  "TypeId": 2
}


### Test PUT update client by ID (Good Case)
PUT {{CRM_API_HostAddress}}/Client
Content-Type: application/json

{
  "ClientID":"bf77af43-8215-433e-9471-c9d036be2d69",
  "TitleId": 2,
  "ClientName": "Jane",
  "ClientSurname": "Doe",
  "ClientEmail": "jane2.doe@example.com",
  "ClientContactNumber": "0987654321",
  "ClientAddress": "456 Main St, City, Country",
  "ClientProfilePicture": "iVBORw0KGgoAAAANSUhEUgAA",
  "TypeId": 4
}

### Test PUT update client by ID (Bad Case - Invalid Client ID)
PUT {{CRM_API_HostAddress}}/Client/9e081e68-9437-4f11-97e3-0e7515449806
Content-Type: application/json
Authorization: {{Token}}

{
  "ClientID":"9e081e68-9437-4f11-97e3-0e7515449806",
  "TitleId": 1,
  "ClientName": "Jane",
  "ClientSurname": "Doe",
  "ClientEmail": "jane.doe@example.com",
  "ClientContactNumber": "0987654321",
  "ClientAddress": "456 Main St, City, Country",
  "ClientProfilePicture": "base64encodedimage",
  "TypeId": 4
}

### Test DELETE client by ID (Good Case)
DELETE {{CRM_API_HostAddress}}/Client/delete/fd18ee22-2e09-45d0-a67d-57109bf35e67
Content-Type: application/json



### Test DELETE client by ID (Bad Case - Invalid Client ID)
DELETE {{CRM_API_HostAddress}}/Client/6910035f-1609-4f88-a6d8-afa3c5228c20
Content-Type: application/json
Authorization: {{Token}}






