@CRM_API_HostAddress = https://localhost:7129

### Test login for client
POST {{CRM_API_HostAddress}}/Login/client
Content-Type: application/json

{
  "LoginUsername":"john.com",
  "LoginPassword":"password"
}

### Test login for employee
POST {{CRM_API_HostAddress}}/Login/employee
Content-Type: application/json

{
  "loginUsername": "Samdoe",
  "loginPassword": "SecurePassword123"
}

